### ISSUE TITLE
Add a docker compose file to the Docker instructions

### ISSUE THREAD

**Issue by mattray** [opencost/opencost-website#218]
Per LinkedIn:
```
------------ docker-compose for OpenCost-----------
version: '3'

services:
 opencost-ui:
  image: [ghcr.io/opencost/opencost-ui:latest](http://ghcr.io/opencost/opencost-ui:latest)
  ports:
   - "9090:9090"
  environment:
   - CLOUD_COST_ENABLED=true [#default](https://www.linkedin.com/feed/hashtag/?keywords=default) is false since it's beta
   - CLOUD_COST_CONFIG_PATH=/path/to/file
-------------------end of file-------------------------------

access UI: http://localhost:9090
```

This needs to be tested before adding to the docs.
