### ISSUE TITLE
Enable OpenCost can work with custom price from cloud providers

### ISSUE THREAD

**Issue by gyliu513** [opencost/opencost-website#232]
**Is your feature request related to a problem? Please describe.**
In many cases customers has special pricing due to agreements with their cloud provider, those agreements are under NDA and don't follow the list price.

**Describe the solution you'd like**
Enable end user can config the price based on their NDA

**Describe alternatives you've considered**

**Additional context**
Add any other context, documentation links, or screenshots about the feature request here.

**Comment by mattray** [comment]
Transferred, now we just need to add it to docs

**Comment by anhvutuan-grabtaxi** [comment]
HI @mattray, can you explain further about the above step ? I can't seem to get it work. My `values.yml` file
```
    env:
      - name: CPU
        value: "0.000176"
      - name: spotCPU
        value: "0.000176"
      - name: RAM
        value: "0.00078"
      - name: spotRAM
        value: "0.00078"
      - name: GPU
        value: "0"
      - name: storage
        value: "0"
      - name: zoneNetworkEgress
        value: "0"
      - name: regionNetworkEgress
        value: "0"
      - name: internetNetworkEgress
        value: "0"
```

**Comment by mattray** [comment]
It's similar to this in your Helm chart:
```
opencost:
  cloudCost:
    enabled: true
  customPricing:
    enabled: true
    configmapName: pricing-configs
    provider: aws
    costModel:
      description: Modified AWS prices
      CPU: 1000.25
      RAM: 0.50
      storage: 0.25
      GPU: 0.95
      spotCPU: 0.006655
      spotRAM: 0.000892
      zoneNetworkEgress: 0.01
      regionNetworkEgress: 0.01
      internetNetworkEgress: 0.143
      spotLabel: 'kops.k8s.io/instancegroup'
      spotLabelValue: 'spotinstance-nodes'
      awsServiceKeyName: ''
      awsServiceKeySecret: ''
      awsSpotDataRegion: ''
      awsSpotDataBucket: ''
      awsSpotDataPrefix: ''
      athenaBucketName: ''
      athenaRegion: ''
      athenaDatabase: ''
      athenaTable: ''
      projectID: 12345
```
