### ISSUE TITLE
You should update helm.md do

### ISSUE THREAD

**Issue by fwernert** [opencost/opencost-website#369]
Hello sir,

I saw that the helm.md doc is 2 years ago, i think that some stuffs as to be update.

Namespace: monitoring
Chart:
- kube-prometheus-stack-70.7.0
- opencost-2.1.1

For example for the metrics.emit part which is very important because if not set it will double the KSM and envVars didn't work for me:

```yaml
    metrics:
      kubeStateMetrics:
        emitKsmV1Metrics: false
        emitKsmV1MetricsOnly: false 
```

For example here is my effective helm values (ansibelised):

```yaml
opencost_vars:
  opencost:
    prometheus:
      internal:
        namespaceName: monitoring
        serviceName: prometheus-kube-prometheus-prometheus
        port: 9090

    dataRetention:
      dailyResolutionDays: 30 # default : 15

    exporter:
      defaultClusterId: "{{ opencost_defaultclusterid }}"
      replicas: 1
      resources:
        requests:
          cpu: "10m"
          memory: "55Mi"
        limits:
          memory: "1Gi"
      persistence:
        enabled: true
        storageClass: "csi-cinder-high-speed"
        accessMode: ReadWriteOnce
        size: 5Gi

    customPricing:
      enabled: true
      provider: "custom"
      costModel: "{{ opencost_costmodel }}"
    metrics:
      kubeStateMetrics:
        emitKsmV1Metrics: false
        emitKsmV1MetricsOnly: false
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus
```

Just my 2 cents.

Have a nice day.
